version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  Build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            
  Linters:
  executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run lint
  
workflows:
    install-and-build:
      jobs:
        - Build
        - Linters
